# CMake generated Testfile for 
# Source directory: /home/spice/workspace/oceanbase/unittest/clog
# Build directory: /home/spice/workspace/oceanbase/unittest/clog
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_ob_log_cache]=] "test_ob_log_cache")
set_tests_properties([=[test_ob_log_cache]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;1;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_ob_log_file_pool]=] "test_ob_log_file_pool")
set_tests_properties([=[test_ob_log_file_pool]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;2;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_ob_index_entry]=] "test_ob_index_entry")
set_tests_properties([=[test_ob_index_entry]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;3;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_ob_log_entry_header]=] "test_ob_log_entry_header")
set_tests_properties([=[test_ob_log_entry_header]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;4;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_ob_log_entry]=] "test_ob_log_entry")
set_tests_properties([=[test_ob_log_entry]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;5;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_ob_log_direct_reader]=] "test_ob_log_direct_reader")
set_tests_properties([=[test_ob_log_direct_reader]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;6;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_log_replay_engine_wrapper]=] "test_log_replay_engine_wrapper")
set_tests_properties([=[test_log_replay_engine_wrapper]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;7;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_log_common]=] "test_log_common")
set_tests_properties([=[test_log_common]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;8;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_ob_log_file_trailer]=] "test_ob_log_file_trailer")
set_tests_properties([=[test_ob_log_file_trailer]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;9;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_ob_log_block_meta_v2]=] "test_ob_log_block_meta_v2")
set_tests_properties([=[test_ob_log_block_meta_v2]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;10;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_ob_raw_entry_iterator]=] "test_ob_raw_entry_iterator")
set_tests_properties([=[test_ob_raw_entry_iterator]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;11;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_log_define]=] "test_log_define")
set_tests_properties([=[test_log_define]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;12;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_log_ext_ring_buffer]=] "test_log_ext_ring_buffer")
set_tests_properties([=[test_log_ext_ring_buffer]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;13;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_log_task]=] "test_log_task")
set_tests_properties([=[test_log_task]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;14;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_log_checksum_V2]=] "test_log_checksum_V2")
set_tests_properties([=[test_log_checksum_V2]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;15;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_get_role]=] "test_get_role")
set_tests_properties([=[test_get_role]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;17;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_member_list]=] "test_member_list")
set_tests_properties([=[test_member_list]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;18;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_info_block_handler]=] "test_info_block_handler")
set_tests_properties([=[test_info_block_handler]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;19;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_ob_log_broadcast_info_mgr]=] "test_ob_log_broadcast_info_mgr")
set_tests_properties([=[test_ob_log_broadcast_info_mgr]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;20;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_clog_writer]=] "test_clog_writer")
set_tests_properties([=[test_clog_writer]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;21;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_seg_array]=] "test_seg_array")
set_tests_properties([=[test_seg_array]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;22;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
add_test([=[test_network_limit_manager]=] "test_network_limit_manager")
set_tests_properties([=[test_network_limit_manager]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;23;ob_unittest;/home/spice/workspace/oceanbase/unittest/clog/CMakeLists.txt;0;")
