# CMake generated Testfile for 
# Source directory: /home/spice/workspace/oceanbase/unittest/share
# Build directory: /home/spice/workspace/oceanbase/unittest/share
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_worker]=] "test_worker")
set_tests_properties([=[test_worker]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;2;ob_unittest;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_scanner]=] "test_scanner")
set_tests_properties([=[test_scanner]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;3;ob_unittest;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_log_file_store]=] "test_log_file_store")
set_tests_properties([=[test_log_file_store]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;6;ob_unittest;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_obj_cast]=] "test_obj_cast")
set_tests_properties([=[test_obj_cast]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;7;ob_unittest;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_log_disk_manager]=] "test_log_disk_manager")
set_tests_properties([=[test_log_disk_manager]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;8;ob_unittest;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_datum_cmp]=] "test_datum_cmp")
set_tests_properties([=[test_datum_cmp]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;9;ob_unittest;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_ob_log_archive_config]=] "test_ob_log_archive_config")
set_tests_properties([=[test_ob_log_archive_config]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;11;ob_unittest;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_ob_tg_mgr]=] "test_ob_tg_mgr")
set_tests_properties([=[test_ob_tg_mgr]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;12;ob_unittest;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_storage_file]=] "test_storage_file")
set_tests_properties([=[test_storage_file]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;13;ob_unittest;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_cluster_id_hash_conflict]=] "test_cluster_id_hash_conflict")
set_tests_properties([=[test_cluster_id_hash_conflict]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;14;ob_unittest;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_json_base]=] "test_json_base")
set_tests_properties([=[test_json_base]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;45;ob_unittest;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_json_bin]=] "test_json_bin")
set_tests_properties([=[test_json_bin]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;46;ob_unittest;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_json_path]=] "test_json_path")
set_tests_properties([=[test_json_path]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;47;ob_unittest;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
add_test([=[test_json_tree]=] "test_json_tree")
set_tests_properties([=[test_json_tree]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/spice/workspace/oceanbase/unittest/CMakeLists.txt;8;add_test;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;48;ob_unittest;/home/spice/workspace/oceanbase/unittest/share/CMakeLists.txt;0;")
subdirs("auto_increment")
subdirs("cache")
subdirs("client_feedback")
subdirs("partition_table")
subdirs("backup")
subdirs("schema")
subdirs("interrupt")
